### ISSUE TITLE
windows SDK version 8.1 should be documented as 'install requirement'

### ISSUE THREAD

**Issue by HNeukermans** [michaelbromley/skqw#2]
Currently after doing npm install on W7 machine, I get an error.

![image](https://cloud.githubusercontent.com/assets/2285199/16651665/cd19c96a-4445-11e6-9a25-19d62cb3100a.png).

Apparently windows 8.1 SDK is required for the installation. This shuould be documented.

**Comment by michaelbromley** [comment]
Thanks - I've only built it on a Windows 10 machine so far. Does it build once you install the Windows 8.1 SDK?
