### ISSUE TITLE
Troubleshooting without Stereo Mix

### ISSUE THREAD

**Issue by shredmer** [michaelbromley/skqw#4]
I am able to use my microphone as an input device successfully. However SKQW is unable to read from the audio playing on my PC. Troubleshooting notes: 

"In the Windows "sound" dialog (right click icon in system tray), go to "recording devices" tab and make sure "stereo mix" is enabled and not muted."

However it seems my sound card does not support Stereo Mix. Is there an alternative way to fix this issue?

![no_stereomix](https://cloud.githubusercontent.com/assets/9870126/17125183/e3b2c5e4-52b6-11e6-8cd7-d73cee3e1ec1.png)

**Comment by michaelbromley** [comment]
Try following this video (second half): https://www.youtube.com/watch?v=Bd3moKLV5sE

Let me know if that is a fix.

**Comment by shredmer** [comment]
Yep that works! I was about to reinstall my mobo drivers, thanks for the easy solution
